USE NetFlix


--==============================================  FUNÇÕES SQL 

SELECT TOP 10 * FROM TB_Flix 

-- SUM 

SELECT 
   COUNT(UF) AS [NUMERO DE ESTADOS]
FROM TB_Flix

-- COUNT 

SELECT 
   SUM(TOTAL_USUARIOS) AS [NUMERO DE ESTADOS]
FROM TB_Flix

----- REPLACE -----------

SELECT 
    ESTADOS,
	TOTAL_USUARIOS,
	REPLACE(PERIODO_DE_ACESSOS,'MANHA','PRIMEIRO ACESSOS') AS PRIMEIROS_ACESSOS,
	PERIODO_DE_ACESSOS,
	TIPO_DE_CONTA,
	VALOR
FROM TB_Flix


----------------------- GROUP BY  

SELECT 
    ESTADOS,
	PERIODO_DE_ACESSOS,
	COUNT(TIPO_DE_CONTA) AS CONTAS,
    TIPO_DE_CONTA
FROM TB_Flix
GROUP BY ESTADOS,TIPO_DE_CONTA, PERIODO_DE_ACESSOS


-------------------------  CONCATENAR


SELECT 
   CONCAT(ESTADOS, ' - ', UF) 
FROM TB_Flix




